// Shared library for Malicious Miscellany generators. require() this from each batch.
const fs=require('fs');const yaml=require('js-yaml');
const OUT='src/packs/apocryphal-adversaries-threats';
const CH='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
function id(){let s='';for(let i=0;i<16;i++)s+=CH[Math.floor(Math.random()*CH.length)];return s;}
const dump=(o)=>yaml.dump(o,{lineWidth:-1,quotingType:'"',forceQuotes:false});
// stable folder ids (shared across all batches)
const FOLDERS={slaugth:'MscSlaugth0Aa1Bb',hrud:'MscHrud00Aa1Bb2C',seraphon:'MscSeraphon0Aa1B',agents:'MscAgentsImp0Aa1'};
const AL={strength:'ATTRIBUTE.STRENGTH',toughness:'ATTRIBUTE.TOUGHNESS',agility:'ATTRIBUTE.AGILITY',initiative:'ATTRIBUTE.INITIATIVE',willpower:'ATTRIBUTE.WILLPOWER',intellect:'ATTRIBUTE.INTELLECT',fellowship:'ATTRIBUTE.FELLOWSHIP'};
function mkAttrs(a){const o={};for(const k of Object.keys(AL))o[k]={label:AL[k],rating:0,base:a[k],bonus:0,cost:0,total:0};return o;}
const SK={athletics:['SKILL.ATHLETICS','strength'],awareness:['SKILL.AWARENESS','intellect'],ballisticSkill:['SKILL.BALLISTIC_SKILL','agility'],cunning:['SKILL.CUNNING','fellowship'],deception:['SKILL.DECEPTION','fellowship'],insight:['SKILL.INSIGHT','fellowship'],intimidation:['SKILL.INTIMIDATION','willpower'],investigation:['SKILL.INVESTIGATION','intellect'],leadership:['SKILL.LEADERSHIP','willpower'],medicae:['SKILL.MEDICAE','intellect'],persuasion:['SKILL.PERSUASION','fellowship'],pilot:['SKILL.PILOT','agility'],psychicMastery:['SKILL.PSYCHIC_MASTERY','willpower'],scholar:['SKILL.SCHOLAR','intellect'],stealth:['SKILL.STEALTH','agility'],survival:['SKILL.SURVIVAL','willpower'],tech:['SKILL.TECH','intellect'],weaponSkill:['SKILL.WEAPON_SKILL','initiative']};
function mkSkills(at,p,dp){const o={};for(const[n,[l,a]]of Object.entries(SK)){const pool=p[n]!=null?p[n]:dp;o[n]={label:l,attribute:a,rating:Math.max(0,pool-at[a]),base:0,bonus:0,cost:0,total:0};}return o;}
function kw(n,d){return{name:n,type:'keyword',_id:id(),img:'icons/svg/eye.svg',system:{description:`<p>${d}</p>`},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
function tal(n,d){return{name:n,type:'talent',_id:id(),img:'modules/wng-core/assets/icons/talents/talent.webp',system:{effect:'',cost:0,requirements:'',description:`<p>${d}</p>`,display:true},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
function abl(n,d,t){return{name:n,type:'ability',_id:id(),img:'modules/wng-core/assets/icons/abilities/ability.webp',system:{dn:0,type:'',specification:'',effect:'',cost:0,requirements:'',description:`<p>${d}</p>`,display:true,abilityType:t||'',traits:[],damage:{base:0,bonus:0,rank:'none'},ed:{base:0,bonus:0,rank:'none'},ap:{base:0,bonus:0,rank:'none'},otherDamage:{mortalWounds:'',wounds:'',shock:''},test:{dn:null,type:''}},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
function arm(n,r,d,inv){return{name:n,type:'armour',_id:id(),img:'modules/wng-core/assets/icons/armour/armour.webp',system:{quantity:1,rarity:'common',description:d||'',value:0,keywords:'',equipped:true,rating:r,base:0,traits:[],invulnerable:!!inv},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
function wM(n,dm,ed,ap,re,tr,eq,d){return{name:n,type:'weapon',_id:id(),img:'modules/wng-core/assets/icons/weapons/melee-weapon.webp',system:{quantity:1,rarity:'common',description:d||'',value:0,keywords:'',equipped:eq,attack:{base:0,bonus:0,rank:'none'},damage:{base:dm,bonus:0,rank:'none'},ed:{base:ed,bonus:0,rank:'none'},ap:{base:ap,bonus:0,rank:'none'},category:'melee',range:{short:0,medium:0,long:0,melee:re,thrown:null},ammo:'',salvo:0,traits:tr||[],upgrades:[]},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
function wR(n,dm,ed,ap,s,m,l,sv,tr,eq,d,thr){return{name:n,type:'weapon',_id:id(),img:(s===0&&m===0&&l===0)?'modules/wng-core/assets/icons/weapons/grenade.webp':'modules/wng-core/assets/icons/weapons/ranged-weapon.webp',system:{quantity:1,rarity:'common',description:d||'',value:0,keywords:'',equipped:eq,attack:{base:0,bonus:0,rank:'none'},damage:{base:dm,bonus:0,rank:'none'},ed:{base:ed,bonus:0,rank:'none'},ap:{base:ap,bonus:0,rank:'none'},category:'ranged',range:{short:s,medium:m,long:l,melee:0,thrown:null},ammo:'',salvo:sv,traits:tr||[],upgrades:[]},effects:[],folder:null,sort:0,ownership:{default:0},flags:{}};}
const co=(n)=>({name:n});const ra=(n,r)=>({name:n,rating:r});const cu=(d,n)=>({name:n||d.toLowerCase().replace(/[^a-z]/g,''),custom:true,display:d});
const rel=()=>cu('Reliable','reliable');const fleshbane=()=>cu('Fleshbane','fleshbane');
const SZ={tiny:1,small:1,average:1,large:2,huge:3,gargantuan:4};
function build(s){const A=id();const it=[];for(const k of s.keywords)it.push(kw(k[0],k[1]));if(s.armour)it.push(arm(s.armour[0],s.armour[1],s.armour[2]||('<p>'+s.armour[1]+' AR.</p>'),s.armourInv));for(const w of s.weapons)it.push(w);for(const t of (s.talents||[]))it.push(tal(t[0],t[1]));for(const a of (s.abilities||[]))it.push(abl(a[0],a[1],a[2]||''));it.push(abl('Determination',s.det,'determination'));for(const i of it)i._key=`!actors.items!${A}.${i._id}`;
const sz=s.size||'average';const tw=SZ[sz];const detBonus=(s.detDice)-s.attrs.toughness;
return{folder:s.folder,name:s.name,type:'threat',_id:A,img:s.img,system:{attributes:mkAttrs(s.attrs),skills:mkSkills(s.attrs,s.skills,s.defPool),combat:{defense:{bonus:s.defBonus||0,total:0},defence:{bonus:s.defBonus||0,total:0},resilience:{bonus:s.resBonus||0,total:0},wounds:{value:0,bonus:0,max:s.wounds},determination:{bonus:detBonus,total:0},shock:{value:0,bonus:0,max:s.noShock?0:s.shock},resolve:{bonus:s.resolveBonus||0,total:0},conviction:{bonus:s.convBonus||0,total:0},size:sz,speed:s.speed,fly:0,passiveAwareness:{bonus:0,total:0},stealth:0},bio:{species:'',faction:'Malicious Miscellany',archetype:'',threat:{first:s.tier[0],second:s.tier[1],third:s.tier[2],fourth:s.tier[3],fifth:s.tier[4]}},resources:{ruin:0},corruption:{current:0},mob:null,notes:`<p>${s.notes}</p>`},prototypeToken:{name:s.name,displayName:20,actorLink:false,appendNumber:false,prependAdjective:false,texture:{src:s.img,scaleX:tw,scaleY:tw,offsetX:0,offsetY:0,rotation:0},width:tw,height:tw,lockRotation:false,rotation:0,alpha:1,disposition:-1,displayBars:20,bar1:{attribute:'combat.wounds'},bar2:{attribute:'combat.shock'},sight:{enabled:false,range:0,angle:360,visionMode:'basic'},detectionModes:[],flags:{},randomImg:false},items:it,effects:[],sort:0,ownership:{default:0},flags:{'wrath-and-glory':{autoCalc:{defence:true,resilience:true,shock:!s.noShock,awareness:true,resolve:true,determination:true,wounds:true,conviction:true},autoWounded:true,autoExhausted:true,generateMetaCurrencies:true}},_key:`!actors!${A}`};}
function emit(specs){for(const s of specs){const d=build(s);fs.writeFileSync(`${OUT}/${s.file}`,dump(d));console.log('wrote',s.file,'-',d.items.length,'items');}}
module.exports={id,dump,FOLDERS,kw,tal,abl,arm,wM,wR,co,ra,cu,rel,fleshbane,build,emit,OUT,fs};
